@baseUrl = http://localhost:3333

@authToken = {{signin.response.body.access_token}}

# @name signin
POST {{baseUrl}}/signin
Content-Type: application/json

{
    "email": "daniel@test.com",
    "password": "123456"
}

### 

# @name create_survivor
POST {{baseUrl}}/survivors
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Jessica Fonteles",
    "email": "jessica@test.com",
    "password": "123456",
    "age": 41,
    "gender": "M",
    "lastLocation": {
        "latitude": -3.745,
        "longitude": -38.523
    },
    "inventory": [
        {
            "id": 1,
            "quantity": 5
        },
        {
            "id": 2,
            "quantity": 5
        },
        {
            "id": 3,
            "quantity": 5
        },
        {
            "id": 4,
            "quantity": 5
        }
    ],
    "infected": false
}

###

# @name trade
POST {{baseUrl}}/trade-items
Content-Type: application/json
Authorization: Baerer {{authToken}}

{
    "userId": "d846d16b-b236-4a15-b502-01f82fe2c2f9",
    "survivorRequestedId": "69bf08f9-14af-43c8-aeee-85b1910a22fb",
    "itemId": "57611bfa-0638-4547-ae4b-08fdba1855ce",
    "quantity": 1
}