@baseUrl = http://localhost:3333

@authToken = {{signin.response.body.access_token}}

# @name signup
POST {{baseUrl}}/signup
Content-Type: application/json

{
    "name": "Diogo Fonteles",
    "email": "diogo@test.com",
    "password": "123456"
}

###

# @name signin
POST {{baseUrl}}/signin
Content-Type: application/json

{
    "email": "daniel@test.com",
    "password": "123456"
}

### 

# @name create_survivor
POST {{baseUrl}}/survivors
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Jessica Fonteles",
    "email": "jessica@test.com",
    "password": "123456",
    "age": 41,
    "gender": "M",
    "lastLocation": {
        "latitude": -3.745,
        "longitude": -38.523
    },
    "inventory": [
        {
            "id": 1,
            "quantity": 5
        },
        {
            "id": 2,
            "quantity": 5
        },
        {
            "id": 3,
            "quantity": 5
        },
        {
            "id": 4,
            "quantity": 5
        }
    ],
    "infected": false
}

###
# @name trade_items
POST {{baseUrl}}/trade-items
Content-Type: application/json
Authorization Bearer {{authToken}}

{
    "userId": 1,
    "survivorRequestedId": 2,
    "itemId": 1,
}