version: '3.8'

services:
  postgres:
    container_name: survival-nexus-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: survival-nexus
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres